#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

#device
git clone https://github.com/dib12/device_xiaomi_vince-11 --single-branch -b r11 device/xiaomi/vince
git clone https://github.com/dib12/vendor_xiaomi_vince-11 --single-branch -b 11 vendor/xiaomi/vince
git clone https://github.com/Blacksuan19/kernel_dark_ages_vince.git --single-branch -b darky kernel/xiaomi/vince
cd kernel/xiaomi/vince && git checkout darky && git revert fec013b9f5bb70c1e51285aa6e042f21f4298447 --no-edit && cd ../../..

#hals
rm -rf hardware/qcom-caf/msm8996/audio &&  git clone https://github.com/aseelps/hardware_qcom_audio_msm8996-vince hardware/qcom-caf/msm8996/audio
rm -rf hardware/qcom-caf/msm8996/media && git clone https://github.com/aseelps/hardware_qcom_media_msm8996-vince hardware/qcom-caf/msm8996/media
rm -rf hardware/qcom-caf/msm8996/display &&  git clone https://github.com/aseelps/hardware_qcom_display_msm8996-vince hardware/qcom-caf/msm8996/display


